{{- if eq .chezmoi.os "windows" -}}
["AppData/Local/nvim"]
{{- else -}}
[".config/nvim"]
{{- end }}
type = "git-repo"
url = "https://github.com/ilkka/nvim-config"
refreshPeriod = "168h"

[".zplug"]
type = "git-repo"
url = "https://github.com/zplug/zplug"
refreshPeriod = "168h"
[".zplug".pull]
args = ["--depth", "1"]

{{ if ne .chezmoi.os "windows" -}}
[".config/alacritty/alacritty-theme"]
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme"
refreshPeriod = "168h"
[".config/alacritty/alacritty-theme".pull]
args = ["--depth", "1"]
{{- end }}

[".poshthemes"]
type = "archive"
url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip"
refreshPeriod = "168h"
exact = true

[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv.git"
refreshPeriod = "168h"

[".pyenv/plugins/pyenv-virtualenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv-virtualenv.git"
refreshPeriod = "168h"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "168h"

{{ if eq .chezmoi.os "windows" -}}
["AppData/Roaming/.emacs.d"]
{{- else -}}
[".emacs.d"]
{{- end }}
type = "git-repo"
url = "https://github.com/syl20bnr/spacemacs"
refreshPeriod = "168h"
