[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim"
  refreshPeriod = "168h"

[".config/nvim/lua/user"]
  type = "git-repo"
  url = "https://github.com/ilkka/astronvim-config.git"
  refreshPeriod = "168h"

[".local/bin/oh-my-posh"]
  type = "file"
  url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64"
  executable = true
  refreshPeriod = "168h"
