[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim"
  refreshPeriod = "168h"

[".config/nvim/lua/user"]
  type = "git-repo"
  url = "https://github.com/ilkka/astronvim-config.git"
  refreshPeriod = "168h"

[".local/bin/oh-my-posh"]
  type = "file"
  url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64"
  executable = true
  refreshPeriod = "168h"

[".poshthemes"]
  type = "archive"
  url = "https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip"
  refreshPeriod = "168h"
  exact = true

[".pyenv"]
  type = "git-repo"
  url = "https://github.com/pyenv/pyenv.git"
  refreshPeriod = "168h"

[".pyenv/plugins/pyenv-virtualenv"]
  type = "git-repo"
  url = "https://github.com/pyenv/pyenv-virtualenv.git"
  refreshPeriod = "168h"

[".local/bin/nvim"]
  type = "file"
  url = "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
  executable = true
  refreshPeriod = "168h"
