;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        electric-newline-and-maybe-indent
        keyboard-escape-quit
        kill-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        electric-pair-delete-pair
        indent-for-tab-command
        ivy-done
        mac-mwheel-scroll
        markdown-exdent-or-delete
        smex
        sp-remove-active-pair-overlay
        swiper
        ))
