# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  #if Vagrant.has_plugin?('vagrant-cachier')
  #  config.cache.scope = :box
  #  #config.cache.synced_folder_opts = {
  #  #  type: :nfs,
  #  #  # The nolock option can be useful for an NFSv3 client that wants to avoid the
  #  #  # NLM sideband protocol. Without this option, apt-get might hang if it tries
  #  #  # to lock files needed for /var/cache/* operations. All of this can be avoided
  #  #  # by using NFSv4 everywhere. Please note that the tcp option is not the default.
  #  #  mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  #  #}
  #end
end
